Makefile
src/vak/cli/cli.py
src/vak/cli/learncurve.py
src/vak/cli/predict.py
src/vak/cli/summary.py
src/vak/cli/train.py
src/vak/config/__init__.py
src/vak/config/data.py
src/vak/config/parse.py
src/vak/config/predict.py
src/vak/config/train.py
src/vak/config/validators.py
src/vak/utils/data.py
tests/setup_scripts/Makefile_config.ini
tests/setup_scripts/remake_results.py
tests/setup_scripts/remake_spects.py
tests/test_data/configs/test_learncurve_config.ini
tests/test_data/configs/test_predict_config.ini
tests/unit_tests/test_cli_funcs/test_cli.py
tests/unit_tests/test_cli_funcs/test_make_data.py
tests/unit_tests/test_config/test_data.py
tests/unit_tests/test_config/test_output.py
tests/unit_tests/test_config/test_parse.py
tests/unit_tests/test_config/test_predict.py
tests/unit_tests/test_config/test_train.py
tests/unit_tests/test_utils.py

Use `attrs`-based classes to represent sections of config.ini files
Rewrite `vak.cli` so it can deal with state of config.ini files

Convert config to attrs

---

src/vak/cli/learncurve.py
src/vak/utils/data.py
tests/unit_tests/test_utils/test_data.py

- learncurve gets indices for all train data subsets before starting training
- add test for `utils.data.get_inds_for_dur`

Draw train first

---

src/vak/cli/__init__.py
src/vak/cli/cli.py
src/vak/cli/prep.py
src/vak/core/prep.py
src/vak/utils/mat.py
tests/unit_tests/test_cli_funcs/test_prep.py

- rename `vak.cli.prep.make_data` function to `vak.cli.prep.prep`
- start a `core` sub-package

Fix data prep

---

doc/CHANGELOG.md
src/vak/__main__.py
src/vak/cli/cli.py
tests/unit_tests/test_cli_funcs/test_cli.py

remove unused options from command-line interface: `--glob`, `--txt`, `--dataset`

Simplify cli

---

src/vak/cli/cli.py
src/vak/cli/predict.py
src/vak/cli/train.py
src/vak/config/predict.py
src/vak/config/valid.toml
src/vak/datasets/__init__.py
src/vak/datasets/unannotated_dataset.py
src/vak/datasets/window_dataset.py
src/vak/engine/model.py
src/vak/io/__init__.py
src/vak/io/audio.py
src/vak/io/dataframe.py
src/vak/io/spect.py
src/vak/transforms/functional.py
src/vak/transforms/transforms.py
src/vak/util/__init__.py
src/vak/util/annotation.py
src/vak/util/general.py
tests/setup_scripts/setup_predict_config.toml
tests/unit_tests/test_cli_funcs/test_prep.py
tests/unit_tests/test_io/test_annot.py
tests/unit_tests/test_io/test_audio.py
tests/unit_tests/test_utils/test_bruteforce.py
tests/unit_tests/test_utils/test_labels.py
tests/unit_tests/test_utils/test_split.py

make `vak predict` command work "all the way" -- not only generate predictions from neural network, but also convert and save to files in specified annotation format

Fix predict

---

src/vak/config/valid.toml

specifically, missing DATALOADER section and 'patience' option in TRAIN, see #93

add missing section/options to valid.toml

---

src/vak/engine/model.py

@yardencsGitHub this should fix #151 -- training a model to test the fix now

Fix model patience logging

---

src/vak/split/algorithms/bruteforce.py

In this version ../split/algorithms/bruteforce.py I start by first making sure each label is represented in the required sets (train,test,validate).
Briefly,
The added code loops through all labels and adds files containing these labels to each set iff the set does not already contain the labels.
Then files are added randomly to meet the required duration of the sets

fix bruteforce.py to ensure all tags exist in sets

---

src/vak/datasets/window_dataset.py

First we try to crop from the end of the dataset
Then, we try from the beginning.
If that doesn't work we crop from silence segments larger than the window_size.
This is done by preventing training windows from starting at points within the silence segments.
Since silence segments can follow non-silence segments or precede them the amount of data being ignored actually depend on whether the silence segment happens to be right in the beginning of the file or right in the end. We make sure to account for that.

add the option to crop silence segments in training set curation

---

src/vak/cli/prep.py
src/vak/core/prep.py

Fix eval cli #235

---

setup.py
src/vak/annotation.py
src/vak/core/predict.py
src/vak/io/audio.py
src/vak/io/dataframe.py
src/vak/io/spect.py

this fixes #256 -- the 3.0.0 version of crowsetta makes `csv` a format

Switch crowsetta 3.0.0

---

setup.py
src/vak/constants.py
src/vak/io/audio.py

switch to using `soundfile` library to load .wav files.
fixes #280

Switch soundfile

---

src/vak/metrics/distance/functional.py
tests/test_metrics/test_distance/test_functional.py

fixes #354 and #355 and adds edge-case handling for `segment_error_rate` as well

Add tests levenshtein

---

.github/workflows/ci.yml
pyproject.toml

- in pyproject.toml set python = ">=3.7,<3.10"
- restrict python-version in .github/ci.yml to 3.7-3.9

DEV: set minimum Python version to 3.7, fix #380

---

doc/toml/gy6or6_predict.toml
doc/toml/gy6or6_train.toml

so option values match what we used for TweetyNet paper revisions

DOC: update config files used in tutorial [skip ci]

---

doc/CHANGELOG.md
doc/get_started/autoannotate.rst
doc/get_started/get_started.rst
doc/howto/howto.rst
doc/index.rst
doc/reference/about.rst
doc/reference/reference.rst
doc/tutorial/tutorial.rst

Fixes #418 and also revises and refactors the landing page, `index.rst`

Revise and refactor docs [skip ci]

---

doc/development/contributors.rst
doc/get_started/autoannotate.rst
doc/get_started/index.rst
doc/get_started/installation.rst
doc/index.rst
doc/reference/about.rst

- remove sanskrit from index/about to avoid confusing people (particularly Hindi speakers)
- make minor clean-ups in installation + tutorial
- remove unused doc files

Docs edits

---

README.md

also make minor revisions, tweaks to headline naming

DOC: fix image and article reference in README.md [skip ci]

---

doc/get_started/installation.md

Fixes #477 and makes some other minor tweaks to formatting

Revise installation.md

---

.github/workflows/ci-linux.yml
.github/workflows/ci-macos.yml
pyproject.toml

DEV: drop Python 3.7

---

README.md
doc/howto/howto_user_annot.md

DOC: fix howto on vocal format and links in README

---

doc/get_started/installation.md

Better document conda install

---

doc/reference/config.md
doc/reference/spect_file_format.md
src/vak/io/dataframe.py
src/vak/io/spect.py
tests/fixtures/audio.py
tests/test_io/test_dataframe.py

Fix dataframe spect params

---

tests/test_console_script.py

TST: Add tests/test_console_script.py, fixes #369 [skip ci]

---

src/vak/__main__.py
src/vak/cli/cli.py
tests/test___main__.py
tests/test_console_script.py

Add unit tests for vak/__main__.py

---

tests/fixtures/__init__.py
tests/fixtures/csv.py
tests/fixtures/dataframe.py
tests/test_cli/test_eval.py
tests/test_cli/test_learncurve.py
tests/test_cli/test_predict.py
tests/test_cli/test_prep.py
tests/test_cli/test_train.py
tests/test_core/test_learncurve.py
tests/test_csv.py

Rewrite test_cli to mock core functions

---

src/vak/cli/eval.py
src/vak/cli/learncurve.py
src/vak/cli/predict.py
src/vak/cli/train.py
src/vak/core/eval.py
src/vak/core/predict.py
src/vak/core/train.py
src/vak/validators.py
tests/fixtures/config.py
tests/test_cli/test_eval.py
tests/test_cli/test_learncurve.py
tests/test_cli/test_predict.py
tests/test_cli/test_train.py
tests/test_core/test_eval.py
tests/test_core/test_learncurve.py
tests/test_core/test_predict.py
tests/test_core/test_train.py

validate csv_paths in cli and core functions

---

src/vak/cli/train.py
src/vak/core/train.py
tests/test_cli/test_train.py
tests/test_core/test_train.py

Fix how train handles labelset and labelmap_path config options

---

noxfile.py
src/vak/annotation.py
src/vak/io/spect.py
tests/fixtures/annot.py
tests/fixtures/test_data.py
tests/test_annotation.py

Handle `has_unlabeled` edge case

---

src/vak/core/train.py
src/vak/transforms/transforms.py
tests/fixtures/dataframe.py
tests/test_transforms/test_transforms.py

Add 'split' parameter to `StandardizeSpect` transform

---

src/vak/cli/eval.py
src/vak/cli/learncurve.py
src/vak/cli/predict.py
src/vak/cli/prep.py
src/vak/cli/train.py
src/vak/logging.py
tests/fixtures/dataframe.py
tests/test_cli/cli_asserts.py
tests/test_cli/test_eval.py
tests/test_cli/test_learncurve.py
tests/test_cli/test_predict.py
tests/test_cli/test_prep.py
tests/test_cli/test_train.py

Have cli log vak version

---

doc/conf.py

Doing this as a branch so I can preview build on Readthedocs before merging

DOC: Add version 1.0 announcement [skip ci]

---

src/scripts/download_autoannotate_data.py

There's future annotation, so we don't need union.

replace union to future syntax

---

pyproject.toml
src/vak/core/eval.py
src/vak/models/windowed_frame_classification_model.py
tests/conftest.py
tests/test_core/test_learncurve/test_learncurve.py
tests/test_core/test_train.py
tests/test_models/test_tweetynet.py

BUG: Change labelmap for validation step of FrameWindowClassificationModel only, fix #664

---

.github/workflows/ci-linux.yml
noxfile.py
pyproject.toml

Require Python version >=3.10 (#762), update lower bounds on other dependencies (#763)

DEV: Require Python>=3.10, update other dependencies
