vocalpy/vak

src/vak/cli/prep.py

when config specifies 'labelset' but config has a [PREDICT] section,
raises a warning and changes 'labelset' to None
because without this, dataframe.from_files will try to check whether
the annotations for each audio file have only labels from labelset,
but since there's no annotation for those files (we're trying to
predict the annotations, presumably), the annotation will be "None" and
this will result in an error

add a warning to cli.prep, change PREDICT behavior

---

src/vak/config/parse.py

wrap the code block that opens the config.toml file in a
try-catch exception that raises a more human-interpretable error
-- "parsing the file failed" -- and then re-raise the
specific error from the 'toml' package
using this approach:
https://stackoverflow.com/questions/9157210/how-do-i-raise-the-same-exception-with-a-custom-message-in-python/29442282#29442282

add TomlDecoderError handling to config/parse.py

---

src/vak/util/labels.py
src/vak/util/split.py

that encapsulates control flow logic for getting all labels from a dataset of annotated vocalizations, represented as a Pandas DataFrame
functions deals with two cases:
1. each vocalization, i.e. each row, has an annotation file associated with it
2. a single annotation file appears in all rows

Add function: vak.util.labels.from_df

---

src/vak/cli/prep.py

detect when config file is for train or learncurve, and
train_dur is only duration greater than zero
raise a ValueError when this is the case with a helpful error message
to explain there is no functionality for creating just a training set
of a specified duration

add logic to catch condition in vak.prep, fix #105

---

src/vak/cli/predict.py
src/vak/cli/train.py
src/vak/transforms/__init__.py
src/vak/transforms/functional.py
src/vak/transforms/transforms.py
src/vak/transforms/util.py

fixes #111 provisionally
I can get `vak train` to run with `normalize_spectrograms = false` when testing on cbin audio files and .not.mat annotations.
Since we don't have tests working right now, not clear whether I introduced any regressions -- need to separately test whether it works on predict as well.
Will go ahead and merge this in so I can fix #110 for @yardencsGitHub

Add transforms util with get defaults func #111

---

src/vak/util/general.py

change default value for `util.general.timebin_dur_from_vec` parameter `n_decimals_trunc` from 3 to 5

change default parameter value, fix #104

---

src/vak/engine/model.py

check not only in `_train` function after each
validation step, but also a level up in the
`fit` function after `_train` returns after
each epoch
fixes bug where training kept going even after
`patience_counter > patience` because `fit` would
just call `_train` again for the next epoch

fix how `vak.Model` checks patience, #166

---

src/vak/engine/model.py

log statements in `vak.Model._train` method refer
to "epochs", even though the validation now runs on
specified steps (i.e. mini-batches) not after a
specified number of epochs
changed to talk about "validation steps"

fix log statements as described in #173

---

src/vak/datasets/window_dataset.py

`lbl_tb_cropped` in line 312 should have been just `lbl_tb` --
this variable name error results in dataset duration
being cropped twice.
Changed to correct name.

fix variable name error in WindowDataset, fix #213

---

src/vak/datasets/window_dataset.py

The vector x_inds points to bins in the training dataset where training windows can start.
When the voctors pointing to the data files and positions in them (spect_id_vector, spect_inds_vector) are cropped from their heads and line 488 throws those positions from x_inds it creates a situation where the entries of x_inds have an offset.
The change makes sure that there is no offset and the first bin in x_inds points to the first bin in the data pointing vectors (0)

Make sure x_inds points correctly after cropping

---

src/vak/transforms/defaults.py

- `vak predict` crashes currently when no StandardizeSpect
transform is used, because of line 214 in
`vak.transforms.get_defaults` where, if the `mode` is
`predict`, and `spect_standardizer' is `None`, the
function adds that `None` to the list of transforms,
and then tries to `compose` them
- simply removing the line that adds `spect_standardizer`
to this list fixes the problem
- that's because in line 197, the function already instantiates
a list with `spect_standardizer` if it is not `None`, or (if
it is `None`), just instantiates an empty list

BUG: remove line from transforms.get_defaults, fix #211

---

src/vak/engine/model.py

change line in Model._eval() that sums metric values across batch
and then divides by batch size so that it converts the sum in a
tensor to a numpy array, to avoid RuntimeError because of
dividing a tensor by an integer (the batch size)

have Model._eval() cast metrics to numpy before divide, fix #249

---

src/vak/cli/prep.py
src/vak/config/parse.py

fixes bug where `vak.config.parse` fails silently when passed a list of `sections` that are not in the config file.
e.g. passing the old name for the spectrogram parameters section, `[SPECTROGRAM]`, instead of the current name `[SPECT_PARAMS]`, silently ignores the actual section and instead just returns the default spectrogram parameters.
This bug became obvious after noticing that any spectrogram parameters besides the defaults were not being parsed. This is because internally the `vak.cli.prep` function was passing a list with `SPECTROGRAM` in it to `vak.config.parse` instead of `SPECT_PARAMS`, as just described.
- removes 'sections' parameter from function `vak.config.parse`
- removes the argument for that parameter that was passed in when `vak.cli.prep` called `vak.config.parse`

Remove sections param fix #200

---

doc/get_started/installation.rst

- remove instruction to install with `conda` from
Anaconda cloud channel `nickledave`, because that
version is broken (it's the 0.2.0 version)
- revise the rest of the page as follows
* change section about virtual environments and `conda`
into a "prerequisites section"
* now have two types of installs, installing
off of PyPI with `pip` after installing
all other dependencies with `conda`, or
a development install using the source code
(still with `pip` but here it's `editable`)

revise installation.rst, fix #265

---

src/vak/split/algorithms/bruteforce.py
src/vak/split/algorithms/validate.py
src/vak/split/split.py

rewrite/rename `split.algorithms.validate.validate_split_durations` and rewrite `split.algorithms.bruteforce` based on issues found when fixing unit tests. 
See commit messages for details

Rewrite split functions

---

src/vak/cli/learncurve.py
src/vak/cli/train.py
src/vak/constants.py
src/vak/core/learncurve.py
src/vak/core/train.py
src/vak/paths.py
src/vak/timenow.py
tests/unit/test_paths.py
tests/unit/test_timenow.py

refactor how `results_path` is computed in `core` and `cli` functions for `train` and `learncurve`.
Previously the same code was repeated in all four functions.
This refactors that code into two helper functions, enforcing consistency and obeying "Don't Repeat Yourself".
Those helper functions also use constants declared in `vak.constants`.
This makes it easier to test they behave as expected, and makes it possible for other unit tests to cleanly 
test that expected results were generated, i.e., unit tests for `vak.core.train`, `vak.core.learncurve`, etc.
* adds two modules:
+ `vak.paths`, with function `generate_results_dir_name_as_path`, and
+ `vak.timenow`, with function `get_timenow_as_str`
* adds constant to `vak.constants`, `STRFTIME_TIMESTAMP` and `RESULTS_DIR_PREFIX`, that are …

Refactor results path

---

src/vak/cli/eval.py
src/vak/cli/learncurve.py
src/vak/cli/predict.py
src/vak/cli/prep.py
src/vak/cli/train.py
src/vak/config/dataloader.py
src/vak/config/eval.py
src/vak/config/learncurve.py
src/vak/config/parse.py
src/vak/config/predict.py
src/vak/config/prep.py
src/vak/config/train.py
src/vak/config/validators.py

refactors `parse.from_toml` function into two functions, the original and a new `parse.from_toml_path`, as described in #305

Refactor parse from toml

---

tests/fixtures/__init__.py
tests/fixtures/config.py
tests/fixtures/device.py
tests/test_cli/test_eval.py
tests/test_cli/test_learncurve.py
tests/test_cli/test_predict.py
tests/test_cli/test_train.py
tests/test_core/test_eval.py
tests/test_core/test_learncurve.py
tests/test_core/test_predict.py
tests/test_core/test_train.py

adds a `device` fixture that is parametrized, and those parameters are built up dynamically, so that when `torch.cuda.is_available` is `True`, it includes `gpu`, and otherwise just `cpu` is used
all the `test_core` and `test_cli` tests use this fixture

Make tests run on cpu and when present gpu

---

src/vak/cli/predict.py
src/vak/config/predict.py
src/vak/config/valid.toml
src/vak/constants.py
src/vak/core/predict.py
tests/test_core/test_predict.py

- add ANNOT_CSV_SUFFIX and NET_OUTPUT_SUFFIX to `constants`,
to use in `vak.core.predict`
- modify core.predict so it can save net outputs, fixes #90
- add `save_net_outputs` parameter
- if `save_net_outputs` is True, reshape outputs from
pred_dict returned by model, remove any padding,
then save in a file:
output_dir/{spect path stem}.{model name}.output.npz
- add `save_net_outputs` option to `predict` config section
- make `vak.cli.predict` pass 'save_net_outputs' argument to `core.predict`
- modify `core.predict` unit tests, to test `save_net_outputs` parameter

ENH: `vak.core.predict` can save model outputs, fix #90

---

src/vak/core/learncurve/train_dur_csv_paths.py
tests/test_cli/test_learncurve.py

- remove code block from `train_dur_csv_paths` that
copied old `spect_vector` .npz files
(that might be made for the wrong window size) over the
newly-generated ones (that were for sure made with the
correct window size)
- change how previous run path unit test is parametrized
- I ran with these new parameters and using '176' for window
size does **not** give me the RuntimeError on the test data.
I don't know why :(
- use `pprint.pformat` in `train_dur_csv_paths` so we get
a string we can use in the logger message, instead of
`pprint.pprint` output that gets sent directly to `stdout`,
with the logger message having a `None` instead
(returned by the `pprint` function)

BUG: remove code block from `train_dur_csv_paths`, fix #321

---

src/vak/core/eval.py
src/vak/core/predict.py
src/vak/engine/model.py
tests/test_core/test_learncurve.py

- add `device` parameter to `model.load` method, defaults to None
+ if None, assign returned value of `get_default_device`
- in `load` method, pass `device` as argument for `map_location`
when calling `torch.load`
+ this should fix bug in #323 where checkpoints trained on GPU
are loaded onto CPU by default, causing RuntimeError
- have both `core.eval` and `core.predict` functions pass in
the `device` they were called with, when they call `model.load`.
This should ensure device passed by config is used.

BUG: make `torch.load` use `map_location` parameter, fix #323

---

src/vak/core/learncurve/learncurve.py
src/vak/core/learncurve/train_dur_csv_paths.py
tests/test_core/test_train_dur_csv_paths.py

BUG: fix how `train_dur_csv_paths.from_dir` orders replicates, fixes #340
- refactor `train_dur_csv_paths`
- factor out code from `train_dur_csv_paths.from_dir`
that uses `previous_run_path` to build
dictionary mapping training set durations to
dataset csv paths into function `_dict_from_dir`
+ this makes it possible to unit test this function alone
+ to make sure we address https://github.com/NickleDave/vak/issues/330
- factor out functions from `train_dur_csv_paths.from_df`
that specify names for:
+ `train_dur` directories -- these are made within the
results path directory, one for each specified training
set duration
+ `replicate` directories, made within each `train_dur` directory
+ `subset` .csv filename, one for each replicate
+ this allows us to make expected names explicit +
test …

fix how `train_dur_csv_paths.from_dir` orders replicates, fixes #340

---

.github/workflows/ci.yml
.gitignore
poetry.lock
pyproject.toml

- add `pytest-cov` as dev dependency
+ upper bound Python as <3.9 to get `coverage` to install
- make ci.yml run pytest with --cov option, save xml report
- set .gitignore to ignore coverage outputs

DEV/CI: add and use `codecov`, fix #86

---

Makefile

- update urls for data for testing, to point at re-generated .tar.gz files
There were two main reasons that the .tar.gz files were too big
+ one was a bunch of generated spectrograms that had just been left in the source directory
+ the other was actual source data that takes up a lot of space e.g. the Cassin's Vireo audio files that are barely even being used
I think I discussed the latter on one of the issues this closes, but not the former? So commenting here

shrink data for testing, fix #349 and #341

---

src/vak/core/predict.py
src/vak/labeled_timebins.py

See rationale for this fix on that issue:
https://github.com/NickleDave/vak/issues/393
and related bug report in
https://github.com/NickleDave/vak/issues/386
- change `lbl_tb2segments` to return all `None`s
when `lbl_tb` passed in is all 'unlabeled' class
- also add logic to `lbl_tb2segment` to handle case
where post-processing removes all labeled segments;
in that case again return all `None`s
- change `vak.core.predict` so it just `continue`s
when `lbl_tb2segments` returns all `None`s
+ i.e. do not create an `Annotation` instance for the vocalization

BUG: handle predicted annotations with no segments, fix #393

---

doc/conf.py
doc/index.rst

- include hidden toctrees in sidebar
change theme settings in conf.py.
Theme is supposed to have this option
set to 'true' by default,
but I found I needed to change it,
not sure why.
- add hidden toctree to bottom of doc/index.rst
had removed toctree before and instead link to key
sections with brief written explanations
- fix copyright date in doc/conf.py
Clean-up, not really related to this issue
DOC:

DOC: add nav entries back to sidebar, fix #426 [skip ci]

---

doc/conf.py
doc/reference/config.rst
src/vak/config/config.py

- fix out-of-date config.Config class-level docstring
- DOC: rewrite reference/config.rst
- use :autoclass: directive to show docstrings
of classes that represent config sections,
to help make sure this document does not go out of sync
with code
- add :contents: at top for convenience of navigation
- add spinx extension 'napoleon' in doc/conf.py so we can use
:autoclass: with Numpy-style docstrings

DOC: rewrite reference/config.rst, fixes #271 [skip ci]

---

.github/CONTRIBUTING.md
CODE_OF_CONDUCT.md
doc/development/commit-abbreviations.rst
doc/development/contributors.rst
doc/development/index.rst
doc/discussion/discussion.rst
doc/index.rst

- add CODE_OF_CONDUCT.md
- remove doc/discussion/discussion.rst, unused
- add development/commit-abbreviations.rst
- add development/contributors.rst, fixes #8 #56
- add doc/development/index.rst
- link to development docs in doc/index.rst
- add .github/CONTRIBUTING.md with links to docs

DOC: add CoC and contributing, fix #8 #56 [skip ci]

---

.readthedocs.yaml

Add 'apt_packages' option in 'build' section of .readthedocs.yaml that specifies to install 'libsndfile1'. This should prevent error in #457 during build on readthedocs.

DOC: make readthedocs config install libsndfile, fix #457 [skip ci]

---

doc/get_started/autoannotate.md
src/vak/constants.py

* adds ability to use two other audio formats (FLAC, OGG)
* revises the "getting started" tutorial to make it clearer that `vak` can work with common audio formats

Fix audio formats [skip ci]

---

src/vak/io/dataframe.py
tests/test_core/test_prep.py

Fixes issue where running `prep` on a `data_dir` with just a single annotation file causes a crash, as described in #467

Bugfix #467 -- `vak prep` crashes when `data_dir` contains single annotation file

---

src/vak/cli/eval.py
src/vak/cli/learncurve.py
src/vak/cli/predict.py
src/vak/cli/prep.py
src/vak/cli/train.py
src/vak/core/eval.py
src/vak/core/learncurve/learncurve.py
src/vak/core/learncurve/train_dur_csv_paths.py
src/vak/core/predict.py
src/vak/core/prep.py
src/vak/core/train.py
src/vak/engine/model.py
src/vak/files/spect.py
src/vak/io/audio.py
src/vak/io/dataframe.py
src/vak/io/spect.py
src/vak/logging.py
src/vak/models/models.py
src/vak/models/teenytweetynet.py
src/vak/split/split.py
tests/test_core/test_eval.py
tests/test_core/test_learncurve.py
tests/test_core/test_predict.py
tests/test_core/test_prep.py
tests/test_core/test_train.py

Fix logging so that log statements do not
repeat themselves (fixes #258).
To do this, we needed to remove all the logic
that passed loggers around between functions,
and instead use the stdlib logging module as intended,
as a singleton where child loggers pass messages
up to the root logger. Doing so produces a breaking change:
the `vak.engine.Model.from_config` method
no longer accepts a `logger` parameter.
This also refactors the logging module,
removing `get logger` and replacing it with
`config_log_for_cli`, which lets the cli
configure logging while at the same time
allowing users to configure logging how they want
when they are not using the cli.
--- squash commits ----
- Rewrite vak/logging.py module
+ Remove `log_or_print` function.
Will now just use python Logger methods directly …

BUG/ENH: Fix/refactor logging, fixes #258

---

src/vak/core/prep.py
tests/fixtures/config.py
tests/test_core/test_prep.py

Raises a ValueError when 'labelset' is left un-set in the .toml config file but the "purpose" of the config requires it, i.e., when the config has a "train", "learncurve" or "eval" section
Without this, an error will definitely result any time we try to split the dataset (as in #468) so this avoids expensive step of generating spectrograms + validating them before getting to that error later on
I think it could also have resulted in silent failures, e.g. by creating an evaluation set that, although it does not require a split, will contain labels not found in the training data, artificially inflating any error metrics
Fixes #468

Fix prep error when labelset none

---

src/vak/config/eval.py
src/vak/config/learncurve.py
src/vak/config/predict.py
src/vak/config/prep.py
src/vak/config/train.py
src/vak/core/eval.py
src/vak/core/predict.py
src/vak/core/prep.py
src/vak/core/train.py
tests/fixtures/config.py
tests/test_config/test_eval.py
tests/test_config/test_parse.py
tests/test_core/test_eval.py
tests/test_core/test_learncurve.py
tests/test_core/test_predict.py
tests/test_core/test_prep.py
tests/test_core/test_train.py

Having the `config` `attrs` classes validate that paths exist makes it difficult to work with config files, e.g. to programatically extract metadata about experiments that have already been run, as described in #459.
Instead of doing this, `config` classes should merely convert to appropriate types, but let other parts of `vak` handle any validation.
Change `vak.core` functions to do this validation instead. This involves sticking in a lot of pre-conditions that check if parameters that are files or directories exist. This may seem un-Pythonic, because it is not duck-typing, but the goal is to give users who may not be programmers very clear feedback about what caused a crash.
Squash commits:
- Remove is_a_file + is_a_dir validators from config classes
+ Remove is_a_file + is_a_dir …

ENH: Have `core` not `config` check paths exist, fix #459

---

src/vak/core/prep.py

Have `vak.core.prep` raise ValueError if `vak_df` returned by `dataframe.from_files` is empty.
Fixes #116.
I was unable to reliably find a way to cause this error -- I should have put more detail in that issue when I raised it.
So I am not adding a unit test for this.
But it still seems better to raise an error than to not, since a user will be expecting the dataset to not be "empty", and we don't want it to fail silently, or cause an even more cryptic error downstream.

ENH: `prep` raises error when dataframe is empty, fix #116 [skip ci]

---

src/vak/annotation.py
src/vak/datasets/window_dataset.py
src/vak/io/audio.py
src/vak/io/spect.py
tests/test_annotation.py
tests/test_labeled_timebins.py

Fixes #525, addresses issues discussed in #523.

Rename and refactor `recursive_stem`, add clearer error messages in vak/annotation.py

---

src/vak/files/files.py
src/vak/files/spect.py
tests/fixtures/audio.py
tests/fixtures/spect.py
tests/test_files/test_files.py
tests/test_files/test_spect.py

Makes two functions in `files` handle paths/filenames with spaces in them: `vak.files.files.find_fname` and `vak.files.spect.find_audio_fname`

ENH: Make files functions handle filename arguments with spaces in them, fix #589

---

src/vak/cli/prep.py
src/vak/config/prep.py
src/vak/config/valid.toml
src/vak/core/prep.py
src/vak/io/audio.py
src/vak/io/dataframe.py
tests/test_io/test_audio.py

Add options to prep for how `vak.io.audio.to_spect` calls `dask.bag`

---

src/vak/core/train.py

Adds simple logging of training time by calling `datetime.datetime.now()` before and after calling `trainer.fit()`. Fixes #2

ENH: Log training time in core.train, fix #2

---

README.md

making a PR to see if it renders correctly

DOC: Add version 1.0 announcement to README [skip ci]

---

src/vak/annotation.py

This is a bugfix for #657 
I found another place where we need to handle the edge case of annotation formats that have more than one valid extension (specifically, 'simple-seq') in the function `vak.annotation.files_from_dir`. I handle it basically the same way we did for `vak.annotation.from_df`, except that I need to glob to figure out if there's any files with either extension, which kind of defeats the purpose of calling `vak.files.from_dir`. But this fixes the issue with 'simple-seq' for now.

BUG: Fix usage of crowsetta 5.0

---

src/vak/models/get.py

This pull request uses `inspect.signature` to determine whether a model's network has `num_input_channels` and `num_freqbins` parameters, and then gets the corresponding values from the dataset's input shape to add to the keyword arguments used when instantiating the model.
This approach is fragile but at least makes it possible to use a model that is not built in, as long as that model's network has these keyword arguments.

ENH: Determine network kwargs dynamically in `vak.models.get`

---

src/vak/models/frame_classification_model.py

Inspecting tensorboard log files generated by version 1.0 revealed that we were no longer logging metrics at every validation step and we were not logging training loss at all.
This PR:

BUG/CLN: Add/fix log statements in FrameClassificationModel

---

src/vak/metrics/distance/functional.py

Makes functions in `vak.transforms.distance.functional` return tensors so we don't cause errors when lightning tries to convert from numpy to tensors to log.
Letting lightning do the conversion kind of works, but it can cause a fatal error
for someone using an Apple M1 with 'mps' as the accelerator, see https://forum.vocalpy.org/t/vak-tweetynet-with-an-apple-m1-max/78/4?u=nicholdav
I don't find any explicit statement in either the Lightning or Torchmetrics docs that metrics should always be tensors, and that this guarantees there won't be weird issues (right now we get a warning on start-up that all logged scalars should be float32, but I would expect one should be able to log integers too?).
But from various issues I read, it seems like that should be the case, …

BUG: Make distance metrics return tensors, fix #700 #701

---

src/vak/config/eval.py
src/vak/config/learncurve.py

BUG: fix default for post_tfm_kwargs, fixes Inconsistent syllable error

BUG: fix default for post_tfm_kwargs, fixes Inconsistent syllable error

---

doc/get_started/autoannotate.md
doc/index.md
doc/toml/gy6or6_eval.toml
doc/toml/gy6or6_predict.toml
doc/toml/gy6or6_train.toml
tests/data_for_tests/configs/TweetyNet_eval_audio_cbin_annot_notmat.toml
tests/data_for_tests/configs/TweetyNet_learncurve_audio_cbin_annot_notmat.toml

This also fixes the video link on the index.md, and adds a couple eval/learncurve configs to the tests that have `post_tfm_kwargs` arguments

DOC: Add eval to autoannotate, fix #460

---

pyproject.toml
tests/test_common/test_labels.py

This fixes a test that fails because in some cases `pandas` is converting the `labels` column to a `pandas.arrays.StringArray`.
I am fixing by just broadening the assertion to check whether `isinstance(labels, (numpy.ndarray, pandas.arrays.StringArray))`.
I need to investigate further but it doesn't seem to be breaking anything else right now.
I also added the dependency on the `dask` extra `dataframe` to squelch a warning we get every time we call `dask.bag` and `dask.delayed`.

TST: Fix test in `common.labels`

---

src/vak/common/tensorboard.py
src/vak/config/model.py
src/vak/models/__init__.py
src/vak/models/base.py
src/vak/models/decorator.py
src/vak/models/definition.py
src/vak/models/factory.py
src/vak/models/frame_classification_model.py
src/vak/models/get.py
src/vak/models/parametric_umap_model.py
src/vak/models/registry.py
tests/data_for_tests/configs/ConvEncoderUMAP_eval_audio_cbin_annot_notmat.toml
tests/data_for_tests/configs/ConvEncoderUMAP_train_audio_cbin_annot_notmat.toml
tests/test_config/test_model.py
tests/test_models/conftest.py
tests/test_models/test_base.py
tests/test_models/test_convencoder_umap.py
tests/test_models/test_decorator.py
tests/test_models/test_ed_tcn.py
tests/test_models/test_factory.py
tests/test_models/test_frame_classification_model.py
tests/test_models/test_parametric_umap_model.py
tests/test_models/test_registry.py
tests/test_models/test_tweetynet.py

This PR refactors the model abstraction, basically as described here: https://github.com/vocalpy/vak/issues/737#issuecomment-2094911335
We replace `vak.models.base.Model`, that sub-classed `lightning.LightningModule`, with `vak.models.factory.ModelFactory`, that no longer sub-classes `LightningModule`. Instead, its `__init__` takes a model definition and a model family, the latter of which is a `lightning.LightningModule`, and its `from_config` and `from_instances` methods return new instances of the `family`, with instances of the `network`, `loss`, `optimizer`, and `metrics` attributes of the definition.
This is really just a shim, in the form of several layers of indirection, to fix the broken logging for now. I'm not sure it makes it much easier to add a model (see #751). 
But it does …

CLN: Refactor model abstraction, fix #737 #726

---

doc/get_started/autoannotate.md
doc/toml/gy6or6_eval.toml
doc/toml/gy6or6_predict.toml

Fixes documentation and accompanying config files so it is clearer where the dataset `path` option should go

DOC: Update autoannoate tutorial, fix #768

---

src/vak/train/frame_classification.py

In train/frame_classification, check if target_type in dataset_config["params"] before using to determine whether there are multiple targets

BUG: avoid KeyError in train.frame_classification, fix #779
